rm(list = ls())

library(DropletUtils)
library(scater)
library(ensembldb)
library(AnnotationHub)
library(BiocParallel)
library(tidyverse)
library(patchwork)
library(ggvenn)
library(scds)
library(Seurat)
library(SeuratObject)
#devtools::install_github("keshavmot2/scanalysis")
library(scanalysis)
library(moments)
library(scran)
library(ggplot2)
library(PCAtools)
library(batchelor)
library(bluster)
library(pheatmap)
library(clustree)
library(Cairo)
library(BiocSingular)
library(cowplot)


setwd("/home/izem/Desktop/STAGE/")

