install.packages("curl")
install.packages("BiocManager")
require(BiocManager)
BiocManager::install("org.Hs.eg.db")
BiocManager::install("org.Mm.eg.db")
install.packages("enrichplot")
BiocManager::install("clusterProfiler")
install.packages("stringr")
install.packages("ggplot2")
install.packages("anndata")
BiocManager::install("scater")
BiocManager::install("bluster")
BiocManager::install("scran")
BiocManager::install("SingleCellExperiment")
BiocManager::install("DropletUtils")
BiocManager::install("scuttle")

# to avoid package ‘methods’ in options("defaultPackages") was not found  blabla
#options(defaultPackages = c(getOption('defaultPackages'), 'tidyverse'))
